### ISSUE TITLE
Rename repo to mjml-python (or similar)

### ISSUE THREAD

**Issue by caseyjhol** [FelixSchwarz/mjml-python#33]
I realize this is still a stub implementation, but we're getting closer to full feature parity. I think it would be helpful to have a more descriptive name. Following this, we should be sure we can get this added to the "Ports and Language Bindings" section in the MJML documentation: https://documentation.mjml.io/#ports-and-language-bindings.

**Comment by FelixSchwarz** [comment]
done :-)
