### ISSUE TITLE
Broken compability with newer versions of css_inline library

### ISSUE THREAD

**Issue by ididit4you** [FelixSchwarz/mjml-python#43]
Hi @FelixSchwarz! 
There was broken changes in [css_inline](https://github.com/Stranger6667/css-inline) after v0.9.0 interface was changed and now it does not allow [inline_style_tags](https://github.com/FelixSchwarz/mjml-python/blob/main/mjml/mjml2html.py#L233C38-L233C38) attribute.

[Last working v0.9.0](https://github.com/Stranger6667/css-inline/blob/wasm-v0.9.0/bindings/python/css_inline.pyi#L4C1-L5C1)
[New v0.10.0](https://github.com/Stranger6667/css-inline/blob/wasm-v0.10.0/bindings/python/css_inline.pyi#L4)

Possible solutions:
1. Set fixed version in [setup.cfg](https://github.com/FelixSchwarz/mjml-python/blob/main/setup.cfg#L61) to the v0.9.0
2. Support the new `css_inline.CSSInliner` interface end test how it works

**Comment by FelixSchwarz** [comment]
Thank you for the report. I'll look into that. I think this was also brought up in #42. Should be a big thing to handle (ideally old + new API ?).

**Comment by FelixSchwarz** [comment]
Unfortunately the `inline_style_tags` option was removed without an obvious replacement so for now I released mjml-python v0.9.1 which pins the dependency to the old version.

I just noticed that @caseyjhol already [filed an issue upstream](https://github.com/Stranger6667/css-inline/issues/253) and the upstream author agreed to reinstante the parameter.

**Comment by caseyjhol** [comment]
I'm working on a PR that will pin the css-inline version (but I've been waiting for the latest version with the fix to come out first). I've also discovered another CSS issue related to child selectors that I'll be pushing up a fix for.

**Comment by caseyjhol** [comment]
If we want to pin to an old version, we'll need to pin to 0.8.7 as 0.9.0 has been yanked.

**Comment by Stranger6667** [comment]
FYI, I am working on a [PR](https://github.com/Stranger6667/css-inline/pull/256) that re-introduces the `inline_style_tags` option with the same behavior as before.

**Comment by Stranger6667** [comment]
The `inline_style_tags` option is reintroduced in `css-inline==0.11.0`
