### ISSUE TITLE
css_inline pinned to < 0.12 but newer versions seem to work

### ISSUE THREAD

**Issue by FelixSchwarz** [FelixSchwarz/mjml-python#55]
@caseyjhol We have `css_inline` pinned to `>= 0.11, < 0.12` but the most recent version is `0.13.0` already. I just installed the newer version and all tests still pass. Any objections of removing the upper limit completely?

**Comment by caseyjhol** [comment]
I think it might still make sense to still pin to 0.13, since we've already been burned before by css_inline changing its API, but I don't feel strongly.

**Comment by FelixSchwarz** [comment]
Ok, I just relaxed the version requirement to `< 0.14` in a83d52e4fa718de00ab1629801b6b9cbe0b09773.

Personally I'd relax the version requirement even more but I'm fine with restricting it assuming that you could monitor `css_inline` for new releases and relax the version requirement on a regular basis. Otherwise I'd just remove the upper limit.

**Comment by FelixSchwarz** [comment]
@caseyjhol `css_inline` v0.14.1 was released. I fear that with this version pining, we are failing to stay up to date.

**Comment by caseyjhol** [comment]
I was trying to see if poetry supported pinning sub-dependency versions (similar to NPM's overrides or Yarn's resolutions), but unfortunately no such luck (https://github.com/python-poetry/poetry/issues/697).

I suppose I'm okay with relaxing the version requirement here. I've been burned enough times in the past by changing APIs and broken dependencies that I always use strict versioning for my dependencies any more (especially for dependencies that are v0.x and could change anything at any time). But for something like inlining CSS the risks are probably pretty minimal.
